### ISSUE TITLE
Error "Unsupported format" when reading raw mp3 file

### ISSUE THREAD

**Issue by TR335** [frolovo22/tag#1]
Hi!
When reading a raw mp3 file it returns the error "unsupported format". I believe this is because there is no ID3 header found. Can you please add an function to add such headers?
Thanks

**Comment by frolovo22** [comment]
Hi!
Thanks for this issue, can you send example of this file at alexey_frolov_22@mail.ru?

Also, if you have only raw mp3 data, you can create header and add it to your file. It must work:  
```golang
tags := tag.ID3v24{
	Data: myRawData,
}
tags.SetAlbum("my album")  
tags.SaveFile("path/to/output.mp3")  
```

**Comment by TR335** [comment]
That would be possible yes, but my file is already saved before I apply the tags
